version: "3.8"

services:
    db:
        image: postgres:latest
        container_name: expense_tracker_db
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: expensetracker
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
